version: '3'
services:
  docker-git:
    image: docker-git
    build:
      dockerfile: Dockerfile
    container_name: docker-git
    command: tail -F anything
    volumes:
      - /Users/jacobo/Documents/santander-wp-docker-dev:/usr/src/santander-wp-docker-dev