version: '3'
services:
  docker-git:
    image: docker-git
    build:
      dockerfile: Dockerfile
    container_name: docker-git
    command: tail -F anything
    volumes:
      - /host/path:/guest/path